modLoader = "javafml" #mandatory
loaderVersion = "[43,)" #mandatory This is typically bumped every Minecraft version by Forge. See https://files.minecraftforge.net/ for a list of versions.
license = "AGPLv3" # Review your options at https://choosealicense.com/.
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional
[[mods]] #mandatory
modId = "strawgolem" #mandatory
version = "${file.jarVersion}" #mandatory
displayName = "Strawgolem" #mandatory
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional (see https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/)
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional (displayed in the mod UI)
logoFile = "multiloader.png" #optional (needs to be in the root of your mod jar (root of your 'resources' folder))
credits = "Fr3nderman for the original model!" #optional
authors = "CommodoreThrawn" #optional
description = '''
Adds a helpful lil' straw golem. He's a farmer!
''' #mandatory (Supports multiline text)
[[dependencies.strawgolem]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[43,)" #mandatory
ordering = "NONE" # The order that this dependency should load in relation to your mod, required to be either 'BEFORE' or 'AFTER' if the dependency is not mandatory
side = "BOTH" # Side this dependency is applied on - 'BOTH', 'CLIENT' or 'SERVER'
[[dependencies.strawgolem]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20, 1.20.4)"
ordering = "NONE"
side = "BOTH"
[[dependencies.strawgolem]]
modId = "tlib"
mandatory = true
versionRange = "*"
ordering = "BEFORE"
side = "BOTH"
[[dependencies.strawgolem]]
modId = "geckolib"
mandatory = true
versionRange = "*"
ordering = "BEFORE"
side = "BOTH"
[[dependencies.strawgolem]]
modId = "cloth-config"
mandatory = false
versionRange = "*"
ordering = "BEFORE"
side = "CLIENT"
[[dependencies.strawgolem]]
modId = "modmenu"
mandatory = false
versionRange = "*"
side = "CLIENT"
[[dependencies.strawgolem]]
modId = "jade"
mandatory = false
versionRange = "*"
side = "CLIENT"